### ISSUE TITLE
The next Open-RMF release checklist

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf#357]
The release will target:
* OS: Ubuntu Jammy 22.04
* ROS Distros: Humble, Iron and Rolling

Specifically we will aim to have two types of releases
1. Source release: Suitable branches and `rmf.repos` files with exact tags of each package will be created here. Similar to [21.09](https://github.com/open-rmf/rmf/blob/release/21.09/rmf.repos)
  * `humble-release`
  * `iron-release`
> Note: Instead of repos files consider relying on `rosinstall_generator`.

2. Debian (Binary) release (distributed via ROS Buildfarm):
  * `humble`
  * `iron`
  * `rolling`
 
> Note: The debian release will not include packages from [rmf_demos](https://github.com/open-rmf/demos) given the known issues [#todo: add link] with distributing these packages.

As part of this release, we will aligned with conventions and practices of ROS 2 releases. One exception will be the default branch for development will continue to be `main` in `Open-RMF` as opposed to `rolling`. We will bloom into ROS 2 Rolling from `main`.

## TODO Checklist (to be completed in order)
- [x] Sync `main` branches with `rolling` so that we can deprecate `rolling`. **Update:** We can't delete rolling since for some repos we can't bring over commits with tags from rolling into main due to linear history constraints.
  - [x] https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/16
  - [x] https://github.com/open-rmf/rmf_battery/pull/39
  - [x] https://github.com/open-rmf/rmf_demos/pull/183
  - [x] https://github.com/open-rmf/rmf_internal_msgs/pull/57
  - [x] https://github.com/open-rmf/rmf_simulation/pull/102
  - [x] https://github.com/open-rmf/rmf_task/pull/87
  - [x] https://github.com/open-rmf/rmf_traffic_editor/pull/466
  - [x] https://github.com/open-rmf/rmf_visualization/pull/56
- [x] Convert all pkg's `CHANGELOGS.md` files to `CHANGELOG.rst`. This is to align with [REP 132](https://www.ros.org/reps/rep-0132.html) and will greatly improve the ease of updating changelogs in the future as they will be auto-populated when running [catkin_generate_changelog](https://docs.ros.org/en/rolling/How-To-Guides/Releasing/Subsequent-Releases.html#updating-changelog).
  - [x] https://github.com/open-rmf/rmf_api_msgs/pull/36
  - [x]  https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/15
  - [x] https://github.com/open-rmf/pybind11_json_vendor/pull/10
  - [x] https://github.com/open-rmf/rmf_battery/pull/38
  - [x] https://github.com/open-rmf/rmf_demos/pull/182
  - [x] https://github.com/open-rmf/rmf_internal_msgs/pull/56
  - [x] https://github.com/open-rmf/rmf_simulation/pull/101
  - [x] https://github.com/open-rmf/rmf_traffic/pull/100
  - [x] https://github.com/open-rmf/rmf_traffic_editor/pull/464
  - [x] https://github.com/open-rmf/rmf_utils/pull/28
  - [x] https://github.com/open-rmf/rmf_visualization/pull/57
  - [x] https://github.com/open-rmf/rmf_visualization_msgs/pull/7
- [x] Bump minor version on `main` for all repos before creating `iron` branch. This will keep `iron` pkgs always ahead of `humble` and we can release API breaking features into `iron`.
  - [x] https://github.com/open-rmf/rmf_building_map_msgs/pull/5 
  - [x] https://github.com/open-rmf/rmf_ros2/pull/280
  - [x] https://github.com/open-rmf/rmf_simulation/pull/103
  - [x] https://github.com/open-rmf/rmf_task/pull/88
  - [x] https://github.com/open-rmf/rmf_traffic/pull/101
  - [x] https://github.com/open-rmf/rmf_traffic_editor/pull/467
  - [x] https://github.com/open-rmf/rmf_utils/pull/29
  - [x] https://github.com/open-rmf/rmf_visualization/pull/59
  - [x] https://github.com/open-rmf/rmf_visualization_msgs/pull/8
- [x] Create `iron` branch from `main` on all repos. 
- [x] Update tracks.yaml in the release repos
  - [x] https://github.com/ros2-gbp/ament_cmake_catch2-release/pull/1
    - [x] Reset `humble` to `rolling` 
  - [x] https://github.com/ros2-gbp/menge_vendor-release/pull/1
  - [x] https://github.com/ros2-gbp/nlohmann_json_schema_validator_vendor-release/pull/1
  - [x] https://github.com/ros2-gbp/pybind11_json_vendor-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_api_msgs-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_battery-release/pull/1
    - [x] reset `humble` to match `rolling` -> merged `rolling` into `humble` and did a patch bump.
  - [x] https://github.com/ros2-gbp/rmf_building_map_msgs-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_internal_msgs-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_ros2-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_simulation-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_task-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_traffic-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_traffic_editor-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_utils-release/pull/1
    - [x] Reset `humble` to `main` for `rmf_utils`
  - [x] https://github.com/ros2-gbp/rmf_visualization-release/pull/1
  - [x] https://github.com/ros2-gbp/rmf_visualization_msgs-release/pull/1
    - [x] Reset `humble` to `main` for rmf_visualization_msgs 
- [x] Bloom packages into `iron`
  - [x] https://github.com/ros/rosdistro/pull/37477
  - [x] https://github.com/ros/rosdistro/pull/37478
  - [x] https://github.com/ros/rosdistro/pull/37491
  - [x] https://github.com/ros/rosdistro/pull/37492
  - [x] https://github.com/ros/rosdistro/pull/37493
  - [x] https://github.com/ros/rosdistro/pull/37494
  - [x] https://github.com/ros/rosdistro/pull/37495
  - [x] https://github.com/ros/rosdistro/pull/37496
  - [x] https://github.com/ros/rosdistro/pull/37497
  - [x] https://github.com/ros/rosdistro/pull/37498
  - [x] https://github.com/ros/rosdistro/pull/37499
  - [x] https://github.com/ros/rosdistro/pull/37500
  - [x] https://github.com/ros/rosdistro/pull/37501
  - [x] https://github.com/ros/rosdistro/pull/37502
  - [x] https://github.com/ros/rosdistro/pull/37503
  - [x] https://github.com/ros/rosdistro/pull/37504
- [x] Bump patch version and bloom packages into `humble`
  - [x] https://github.com/ros/rosdistro/pull/37425
  - [x] https://github.com/ros/rosdistro/pull/37426
  - [x] https://github.com/ros/rosdistro/pull/37431
  - [x] https://github.com/ros/rosdistro/pull/37432
  - [x] https://github.com/ros/rosdistro/pull/37433
  - [x] https://github.com/ros/rosdistro/pull/37434
  - [x] https://github.com/ros/rosdistro/pull/37435
  - [x] https://github.com/ros/rosdistro/pull/37441
  - [x] https://github.com/ros/rosdistro/pull/37442
  - [x] https://github.com/ros/rosdistro/pull/37443
  - [x] https://github.com/ros/rosdistro/pull/37455
  - [x] https://github.com/ros/rosdistro/pull/37456
  - [x] https://github.com/ros/rosdistro/pull/37457
  - [x] https://github.com/ros/rosdistro/pull/37458
  - [x] https://github.com/ros/rosdistro/pull/37459
  - [x] https://github.com/ros/rosdistro/pull/37460
- [x] Bump minor version on `main` for all repos so that `main` remains ahead of `iron`.
  - [x] https://github.com/open-rmf/ament_cmake_catch2/pull/5
  - [x] https://github.com/open-rmf/menge_vendor/pull/12
  - [x] https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/17
  - [x] https://github.com/open-rmf/rmf_api_msgs/pull/40
  - [x] https://github.com/open-rmf/rmf_api_msgs/pull/40
  - [x] https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/17
  - [x] https://github.com/open-rmf/menge_vendor/pull/12
  - [x] https://github.com/open-rmf/ament_cmake_catch2/pull/5
  - [x] https://github.com/open-rmf/rmf_building_map_msgs/pull/6
  - [x] https://github.com/open-rmf/rmf_internal_msgs/pull/58
  - [x] https://github.com/open-rmf/rmf_ros2/pull/282
  - [x] https://github.com/open-rmf/rmf_simulation/pull/104
  - [x] https://github.com/open-rmf/rmf_traffic/pull/102
  - [x] https://github.com/open-rmf/rmf_traffic_editor/pull/468
  - [x] https://github.com/open-rmf/rmf_utils/pull/30
  - [x] https://github.com/open-rmf/rmf_visualization_msgs/pull/9
- [x] Bloom packages into `rolling`
  - [x] https://github.com/ros/rosdistro/pull/37545
  - [x] https://github.com/ros/rosdistro/pull/37546
  - [x] https://github.com/ros/rosdistro/pull/37547
  - [x] https://github.com/ros/rosdistro/pull/37548
  - [x] https://github.com/ros/rosdistro/pull/37552
  - [x] https://github.com/ros/rosdistro/pull/37551
  - [x] https://github.com/ros/rosdistro/pull/37550
  - [x] https://github.com/ros/rosdistro/pull/37553
  - [x] https://github.com/ros/rosdistro/pull/37554
  - [x] https://github.com/ros/rosdistro/pull/37555
  - [x] https://github.com/ros/rosdistro/pull/37556
  - [x] https://github.com/ros/rosdistro/pull/37557
  - [x] https://github.com/ros/rosdistro/pull/37558
  - [x] https://github.com/ros/rosdistro/pull/37559
  - [x] https://github.com/ros/rosdistro/pull/37560
  - [x] https://github.com/ros/rosdistro/pull/37561
- [x] Update open-rmf/rmf. 
  - [x] Create `iron` branch
  - [x] Create `iron-release` with exact tags of release pkgs
  - [x] Tag `iron-release` with date of update eg `release-iron-230526`
  - [x] Create `humble` branch
  - [x] Create `humble-release` with exact tags of release pkgs: https://github.com/open-rmf/rmf/blob/humble-release/rmf.repos
  - [x] Tag `humble-release` with date of update eg `release-humble-230526`
  - [x] Update README.md: https://github.com/open-rmf/rmf/pull/360
- [x] Release `rmf_dev` metapackage 
  - [x] https://github.com/ros2-gbp/ros2-gbp-github-org/issues/267

**Comment by Yadunund** [comment]
Done!
