### ISSUE TITLE
Jazzy Jalisco checklist

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf#416]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

This ticket serves as living checklist of items to accomplish to ensure Open-RMF is released on ROS 2 Jazzy Jalisco that will target Ubuntu 24.04. One major change in the new distribution will be the drop in support for Gazebo classic. But it also provides opportunities to release new packages and make improvements with breaking changes that will be listed below.

- [x] rmf_ci_templates:
  - Switch rolling jobs to Noble: https://github.com/open-rmf/rmf_ci_templates/pull/10
  - Add Jazzy option once available.

- [x] rmf_simulation : https://github.com/open-rmf/rmf_simulation/pull/114
  - Drop `*_gz_classic_plugins` packages and refactor `*_gz_plugins` to adopt more favorable ECS patterns.
  - Drop TPE support
  - Support Gazebo Harmonic

- [x] rmf_traffic_editor: https://github.com/open-rmf/rmf_traffic_editor/pull/483
  - Drop `gz_classic` support.
  - Change world generation to adopt ECS patterns.
  - Rename Ignition to Gazebo.
  - Update templates to Harmonic

- [x] rmf_demos: https://github.com/open-rmf/rmf_demos/pull/206
  - Drop `*_gz_classic` packages
  - Drop TPE support
  - Bloom into Rolling to check that packages can be released

- [ ] Release
  - [x] Bloom changes into Rolling
    - [x] https://github.com/open-rmf/rmf_api_msgs/pull/55
      - [x] https://github.com/ros/rosdistro/pull/41443 
    - [x] https://github.com/open-rmf/rmf_internal_msgs/pull/72
      - [x] https://github.com/ros/rosdistro/pull/41444 
    - [x] https://github.com/open-rmf/rmf_ros2/pull/359
      - [x] https://github.com/ros/rosdistro/pull/41572
      - [x] https://github.com/open-rmf/rmf_ros2/pull/365
      - [x] https://github.com/ros/rosdistro/pull/41584
    - [x] https://github.com/open-rmf/rmf_simulation/pull/124
      - [x] https://github.com/ros/rosdistro/pull/41450 
      - [x] https://github.com/ros/rosdistro/pull/41592
      - [x] https://github.com/open-rmf/rmf_simulation/pull/127
    - [x] https://github.com/open-rmf/rmf_task/pull/117
      - [x] https://github.com/open-rmf/rmf_task/pull/119
      - [x] https://github.com/ros/rosdistro/pull/41453
    - [x] https://github.com/open-rmf/rmf_traffic_editor/pull/497
      - [x] https://github.com/ros/rosdistro/pull/41451 
    - [x] https://github.com/open-rmf/rmf_utils/pull/31
      - [x] https://github.com/ros/rosdistro/pull/41452 
    - [x] https://github.com/open-rmf/rmf_visualization/pull/72
      - [x] https://github.com/open-rmf/rmf_visualization/pull/73 
      - [x] https://github.com/ros/rosdistro/pull/41454 
      - [x] https://github.com/open-rmf/rmf_visualization/pull/75
    - [x] https://github.com/open-rmf/rmf_demos/pull/233 
      - [x] https://github.com/open-rmf/rmf_demos/pull/239 
  - [x] Create `jazzy` source branches https://github.com/open-rmf/rmf/blob/jazzy/rmf.repos 
  - [x] Minor version bump on main for all repos.
    - [x] https://github.com/open-rmf/menge_vendor/pull/13
      - [x] https://github.com/ros/rosdistro/pull/41610 
    - [x] https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/18
      - [x] https://github.com/ros/rosdistro/pull/41624 
    - [x] https://github.com/open-rmf/pybind11_json_vendor/pull/13
      - [x] https://github.com/ros/rosdistro/pull/41626 
    - [x] https://github.com/open-rmf/ament_cmake_catch2/pull/6
      - [x] https://github.com/ros/rosdistro/pull/41628 
    - [x] https://github.com/open-rmf/rmf_battery/pull/41
      - [x] https://github.com/ros/rosdistro/pull/41630 
    - [x] https://github.com/open-rmf/rmf_internal_msgs/pull/73
      - [x] https://github.com/ros/rosdistro/pull/41632 
    - [x] https://github.com/open-rmf/rmf_simulation/pull/128
      - [x] https://github.com/ros/rosdistro/pull/41634 
    - [x] https://github.com/open-rmf/rmf_traffic/pull/109
      - [x] https://github.com/ros/rosdistro/pull/41636 
    - [x] https://github.com/open-rmf/rmf_utils/pull/32
       - [x] https://github.com/ros/rosdistro/pull/41639 
    - [x] https://github.com/open-rmf/rmf_api_msgs/pull/56
      - [x] https://github.com/ros/rosdistro/pull/41648 
    - [x] https://github.com/open-rmf/rmf_building_map_msgs/pull/7
      - [x] https://github.com/ros/rosdistro/pull/41652 
    - [x] https://github.com/open-rmf/rmf_ros2/pull/368
    - [x]  https://github.com/open-rmf/rmf_task/pull/120
      - [x] https://github.com/ros/rosdistro/pull/41650 
    - [x] https://github.com/open-rmf/rmf_traffic_editor/pull/499
      - [x] https://github.com/ros/rosdistro/pull/41641 
    - [x] https://github.com/open-rmf/rmf_visualization/pull/76
      - [x] https://github.com/ros/rosdistro/pull/41644 
    - [x] https://github.com/open-rmf/rmf_demos/pull/241
      - [ ] https://github.com/ros/rosdistro/pull/41714 
    - [x] https://github.com/open-rmf/rmf_variants/pull/2
      - [x] https://github.com/open-rmf/rmf_variants/pull/3
      - [x] https://github.com/ros/rosdistro/pull/41609 
    - [x] https://github.com/open-rmf/rmf_visualization_msgs/pull/10
      - [x] https://github.com/ros/rosdistro/pull/41717  
  - [x] Update `rmf_ci_templates` to run jobs for `jazzy` https://github.com/open-rmf/rmf_ci_templates/pull/13
  - [x] Add `jazzy` tracks in `ros2-gbp` release repositories
    - [x] https://github.com/ros2-gbp/rmf_variants-release/pull/1 
    - [x] https://github.com/ros2-gbp/menge_vendor-release/commit/e02780dd08cbcd0740e43e0519bd51f951dd7c79
    - [x] https://github.com/ros2-gbp/nlohmann_json_schema_validator_vendor-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_visualization-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_utils-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_traffic-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_visualization_msgs-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_ros2-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_internal_msgs-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_api_msgs-release/pull/2
    - [x] https://github.com/ros2-gbp/ament_cmake_catch2-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_building_map_msgs-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_task-release/pull/2
    - [x] https://github.com/ros2-gbp/rmf_battery-release/pull/2
    - [x] https://github.com/ros2-gbp/pybind11_json_vendor-release/pull/2
    - [x] rmf_simulation
    - [x] rmf_traffic_editor
  - [x] Update osr_dashboard to include jazzy: https://github.com/osrf/osr_dashboard/pull/26
  - [ ] Bloom packages into Jazzy
    - [x] https://github.com/ros/rosdistro/pull/41611 
    - [ ] https://github.com/ros/rosdistro/pull/41625
    - [ ] https://github.com/ros/rosdistro/pull/41627
    - [ ] https://github.com/ros/rosdistro/pull/41629
    - [ ] https://github.com/ros/rosdistro/pull/41631
    - [ ] https://github.com/ros/rosdistro/pull/41633
    - [x] https://github.com/ros/rosdistro/pull/41635
    - [ ] https://github.com/ros/rosdistro/pull/41638
    - [ ] https://github.com/ros/rosdistro/pull/41640
    - [ ] https://github.com/ros/rosdistro/pull/41642
    - [ ] https://github.com/ros/rosdistro/pull/41646
    - [ ] https://github.com/ros/rosdistro/pull/41649
    - [ ] https://github.com/ros/rosdistro/pull/41651
    - [ ] https://github.com/ros/rosdistro/pull/41653
    - [ ] https://github.com/ros/rosdistro/pull/41715
    - [ ] https://github.com/ros/rosdistro/pull/41716
    - [ ] https://github.com/ros/rosdistro/pull/41735
    - [ ] https://github.com/ros/rosdistro/pull/41733
  - [x] Tag source release https://github.com/open-rmf/rmf/releases/tag/release-jazzy-240617
  - [ ] Update README https://github.com/open-rmf/rmf/pull/479 

Followups for `rmf_demos` release:
  - [ ] Find a way to distribute assets. Downloading models into `~/.gazebo/models` via building_map_tools will not work.
  - [x] Drop `rmf_demos_dashboard` -> default to `rmf_web` https://github.com/open-rmf/rmf_demos/pull/235
  - [x] Verify apt versions of critical python modules are available
  - [ ] Update assets with new plugin tags if any
  - [ ] Create a `rmf-desktop-full` binary variant that installs binaries upto `rmf-dev` and `rmf-demos`
